---
- name: Check health of defined SAP instance
  hosts: all
  become: true
  become_user: root
  gather_facts: false

  tasks:
    # Check local SAP server
    - name: Check local SAP server
      ansible.builtin.command:
        cmd: /opt/sap/bin/sap.sh status
      register: sap_health_command
      changed_when: false
      failed_when: sap_health_command.rc != 0
