---
- name: Stop SAP instance on defined server
  hosts: all
  become: true
  become_user: root
  gather_facts: false

  tasks:
    # Stop local SAP server
    - name: Stop local SAP server
      ansible.builtin.command:
        cmd: /opt/sap/bin/sap.sh stop
      register: sap_stop_command
      changed_when: false
      failed_when: sap_stop_command.rc != 0
