---
- name: Start SAP instance on defined server
  hosts: all
  become: true
  become_user: root
  gather_facts: false

  tasks:
    # Start local SAP server
    - name: Start local SAP server
      ansible.builtin.command:
        cmd: /opt/sap/bin/sap.sh start
      register: sap_start_command
      changed_when: false
      failed_when: sap_start_command.rc != 0
