---
- name: Setup Netweaver resources in the Pacemaker cluster
  hosts: all
  become: true
  become_user: root

  vars:
    sap_anf_options: "rw,vers=4,minorversion=1,hard,timeo=600,rsize=262144,wsize=262144,intr,noatime,lock,_netdev,sec=sys,suid"

  tasks:
    - name: Configure SAP Netweaver cluster
      when:
        - sap_ha
        - sap_instance_type == "ASCS"
      block:
        # Ensure that the cluster is in maintenance mode
        - name: Ensure Cluster is in maintenance mode
          ansible.builtin.command:
            cmd: "/usr/sbin/pcs property set maintenance-mode=true"
          register: sap_ha_cluster_mode
          changed_when: "'error' not in sap_ha_cluster_mode.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary

        # Ensure properties are set correctly
        - name: Ensure Pacemaker stickiness is configured properly
          ansible.builtin.command:
            cmd: "/usr/sbin/pcs resource defaults resource-stickiness=1"
          register: sap_ha_cluster_resource_config
          changed_when: "'Defaults do not apply to resource' in sap_ha_cluster_resource_config.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary

        - name: Ensure Pacemaker migration threshold is configured properly
          ansible.builtin.command:
            cmd: "/usr/sbin/pcs resource defaults migration-threshold=3"
          register: sap_ha_cluster_resource_config
          changed_when: "'Defaults do not apply to resource' in sap_ha_cluster_resource_config.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary

        # Create SAP Netweaver cluster resources
        - name: Set second node as standby
          ansible.builtin.command:
            cmd: |
              /usr/sbin/pcs node standby {{ sap_ha_secondary }}
          register: sap_ha_cluster_node_standby
          changed_when: "'Assumed agent name' in sap_ha_cluster_node_standby.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary

        - name: Create ASCS file resource
          ansible.builtin.shell:
            cmd: |
              /usr/sbin/pcs resource create fs_{{ sap_instance_sid }}_ASCS \
              Filesystem device='{{ sap_anf_netweaver_sapusr }}/ASCS{{ sap_ha_ascs_instance_number }}' \
              directory='/usr/sap/{{ sap_instance_sid }}/ASCS{{ sap_ha_ascs_instance_number }}' \
              fstype='nfs' force_unmount=safe options='{{ sap_anf_options }}' \
              op start interval=0 timeout=60 \
              op stop interval=0 timeout=120 \
              op monitor interval=200 timeout=105 \
              --group g-{{ sap_instance_sid }}_ASCS
          register: sap_ha_cluster_resource_create
          changed_when: "'Assumed agent name' in sap_ha_cluster_resource_create.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary
            - sap_ha_ascs_instance_number is defined

        - name: Create SCS file resource
          ansible.builtin.shell:
            cmd: |
              /usr/sbin/pcs resource create fs_{{ sap_instance_java_sid }}_SCS \
              Filesystem device='{{ sap_anf_netweaver_sapusr }}/SCS{{ sap_ha_scs_instance_number }}' \
              directory='/usr/sap/{{ sap_instance_java_sid }}/SCS{{ sap_ha_scs_instance_number }}' \
              fstype='nfs' force_unmount=safe options='{{ sap_anf_options }}' \
              op start interval=0 timeout=60 \
              op stop interval=0 timeout=120 \
              op monitor interval=200 timeout=105 \
              --group g-{{ sap_instance_sid }}_ASCS
          register: sap_ha_cluster_resource_create
          changed_when: "'Assumed agent name' in sap_ha_cluster_resource_create.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary
            - sap_ha_scs_instance_number is defined

        - name: Create (A)SCS virtual IP resource
          ansible.builtin.shell:
            cmd: |
              /usr/sbin/pcs resource create vip_{{ sap_instance_sid }}_ASCS \
              IPaddr2 ip="{{ sap_ha_vip_primary }}" cidr_netmask={{ sap_ha_vcidr_primary }} \
              op monitor interval=30s \
              --group g-{{ sap_instance_sid }}_ASCS
          register: sap_ha_cluster_resource_create
          changed_when: "'Assumed agent name' in sap_ha_cluster_resource_create.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary

        - name: Create (A)SCS LB resource
          ansible.builtin.shell:
            cmd: |
              /usr/sbin/pcs resource create nc_{{ sap_instance_sid }}_ASCS azure-lb port=62000 \
              --group g-{{ sap_instance_sid }}_ASCS
          register: sap_ha_cluster_resource_create
          changed_when: "'Assumed agent name' in sap_ha_cluster_resource_create.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary

        - name: Activate second node
          ansible.builtin.command:
            cmd: |
              /usr/sbin/pcs node unstandby {{ sap_ha_secondary }}
          register: sap_ha_cluster_node_standby
          changed_when: "'Assumed agent name' in sap_ha_cluster_node_standby.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary

        - name: Set primary node as standby
          ansible.builtin.command:
            cmd: |
              /usr/sbin/pcs node standby {{ sap_ha_primary }}
          register: sap_ha_cluster_node_standby
          changed_when: "'Assumed agent name' in sap_ha_cluster_node_standby.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary

        - name: Create AERS file resource
          ansible.builtin.shell:
            cmd: |
              /usr/sbin/pcs resource create fs_{{ sap_instance_sid }}_AERS \
              Filesystem device='{{ sap_anf_netweaver_sapusr }}/ERS{{ sap_ha_aers_instance_number }}' \
              directory='/usr/sap/{{ sap_instance_sid }}/ERS{{ sap_ha_aers_instance_number }}' \
              fstype='nfs' force_unmount=safe options='{{ sap_anf_options }}' \
              op start interval=0 timeout=60 \
              op stop interval=0 timeout=120 \
              op monitor interval=200 timeout=105 \
              --group g-{{ sap_instance_sid }}_AERS
          register: sap_ha_cluster_resource_create
          changed_when: "'Assumed agent name' in sap_ha_cluster_resource_create.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary
            - sap_ha_aers_instance_number is defined

        - name: Create ERS file resource
          ansible.builtin.shell:
            cmd: |
              /usr/sbin/pcs resource create fs_{{ sap_instance_java_sid }}_ERS \
              Filesystem device='{{ sap_anf_netweaver_sapusr }}/ERS{{ sap_ha_ers_instance_number }}' \
              directory='/usr/sap/{{ sap_instance_java_sid }}/ERS{{ sap_ha_ers_instance_number }}' \
              fstype='nfs' force_unmount=safe options='{{ sap_anf_options }}' \
              op start interval=0 timeout=60 \
              op stop interval=0 timeout=120 \
              op monitor interval=200 timeout=105 \
              --group g-{{ sap_instance_sid }}_AERS
          register: sap_ha_cluster_resource_create
          changed_when: "'Assumed agent name' in sap_ha_cluster_resource_create.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary
            - sap_ha_ers_instance_number is defined

        - name: Create ERS virtual IP resource
          ansible.builtin.shell:
            cmd: |
              /usr/sbin/pcs resource create vip_{{ sap_instance_sid }}_AERS \
              IPaddr2 ip="{{ sap_ha_vip_secondary }}" cidr_netmask={{ sap_ha_vcidr_secondary }} \
              op monitor interval=30s \
              --group g-{{ sap_instance_sid }}_AERS
          register: sap_ha_cluster_resource_create
          changed_when: "'Assumed agent name' in sap_ha_cluster_resource_create.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary

        - name: Create ERS LB resource
          ansible.builtin.shell:
            cmd: |
              /usr/sbin/pcs resource create nc_{{ sap_instance_sid }}_AERS azure-lb port=62000 \
              --group g-{{ sap_instance_sid }}_AERS
          register: sap_ha_cluster_resource_create
          changed_when: "'Assumed agent name' in sap_ha_cluster_resource_create.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary

        - name: Create SAP ASCS instance
          ansible.builtin.shell:
            cmd: |
              /usr/sbin/pcs resource create rsc_sap_{{ sap_instance_sid }}_ASCS{{ sap_ha_ascs_instance_number }} \
              SAPInstance InstanceName={{ sap_instance_sid }}_ASCS{{ sap_ha_ascs_instance_number }}_{{ sap_alias }} \
              START_PROFILE="/sapmnt/{{ sap_instance_sid }}/profile/{{ sap_instance_sid }}_ASCS{{ sap_ha_ascs_instance_number }}_{{ sap_alias }}" \
              AUTOMATIC_RECOVER=false \
              meta resource-stickiness=5000 \
              op start interval=0 timeout=600 \
              op stop interval=0 timeout=600 \
              op monitor interval=20 on-fail=restart timeout=105 \
              --group g-{{ sap_instance_sid }}_ASCS
          register: sap_ha_cluster_resource_create
          changed_when: "'Assumed agent name' in sap_ha_cluster_resource_create.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary
            - sap_ha_ascs_instance_number is defined

        - name: Create SAP SCS instance
          ansible.builtin.shell:
            cmd: |
              /usr/sbin/pcs resource create rsc_sap_{{ sap_instance_java_sid }}_SCS{{ sap_ha_scs_instance_number }} \
              SAPInstance InstanceName={{ sap_instance_java_sid }}_SCS{{ sap_ha_scs_instance_number }}_{{ sap_alias }} \
              START_PROFILE="/sapmnt/{{ sap_instance_java_sid }}/profile/{{ sap_instance_java_sid }}_SCS{{ sap_ha_scs_instance_number }}_{{ sap_alias }}" \
              AUTOMATIC_RECOVER=false \
              meta resource-stickiness=5000 \
              op start interval=0 timeout=600 \
              op stop interval=0 timeout=600 \
              op monitor interval=20 on-fail=restart timeout=105 \
              --group g-{{ sap_instance_sid }}_ASCS
          register: sap_ha_cluster_resource_create
          changed_when: "'Assumed agent name' in sap_ha_cluster_resource_create.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary
            - sap_ha_scs_instance_number is defined

        - name: Create stickiness for ASCS group
          ansible.builtin.shell:
            cmd: |
              /usr/sbin/pcs resource meta g-{{ sap_instance_sid }}_ASCS resource-stickiness=3000
          register: sap_ha_cluster_resource_create
          changed_when: "'Assumed agent name' in sap_ha_cluster_resource_create.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary

        - name: Create SAP AERS instance
          ansible.builtin.shell:
            cmd: |
              /usr/sbin/pcs resource create rsc_sap_{{ sap_instance_sid }}_ERS{{ sap_ha_aers_instance_number }} \
              SAPInstance InstanceName={{ sap_instance_sid }}_ERS{{ sap_ha_aers_instance_number }}_{{ sap_alias }} \
              START_PROFILE="/sapmnt/{{ sap_instance_sid }}/profile/{{ sap_instance_sid }}_ERS{{ sap_ha_aers_instance_number }}_{{ sap_alias }}" \
              AUTOMATIC_RECOVER=false IS_ERS=true \
              op start interval=0 timeout=600 \
              op stop interval=0 timeout=600 \
              op monitor interval=20 on-fail=restart timeout=105 \
              --group g-{{ sap_instance_sid }}_AERS
          register: sap_ha_cluster_resource_create
          changed_when: "'Assumed agent name' in sap_ha_cluster_resource_create.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary
            - sap_ha_aers_instance_number is defined

        - name: Create SAP ERS instance
          ansible.builtin.shell:
            cmd: |
              /usr/sbin/pcs resource create rsc_sap_{{ sap_instance_java_sid }}_ERS{{ sap_ha_ers_instance_number }} \
              SAPInstance InstanceName={{ sap_instance_java_sid }}_ERS{{ sap_ha_ers_instance_number }}_{{ sap_alias }} \
              START_PROFILE="/sapmnt/{{ sap_instance_java_sid }}/profile/{{ sap_instance_java_sid }}_ERS{{ sap_ha_ers_instance_number }}_{{ sap_alias }}" \
              AUTOMATIC_RECOVER=false IS_ERS=true \
              op start interval=0 timeout=600 \
              op stop interval=0 timeout=600 \
              op monitor interval=20 on-fail=restart timeout=105 \
              --group g-{{ sap_instance_sid }}_AERS
          register: sap_ha_cluster_resource_create
          changed_when: "'Assumed agent name' in sap_ha_cluster_resource_create.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary
            - sap_ha_ers_instance_number is defined

        - name: Create stickiness for AERS instance
          ansible.builtin.shell:
            cmd: |
              /usr/sbin/pcs resource meta rsc_sap_{{ sap_instance_sid }}_ERS{{ sap_ha_aers_instance_number }} \
              resource-stickiness=3000
          register: sap_ha_cluster_resource_create
          changed_when: "'Assumed agent name' in sap_ha_cluster_resource_create.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary
            - sap_ha_aers_instance_number is defined

        - name: Create stickiness for ERS instance
          ansible.builtin.shell:
            cmd: |
              /usr/sbin/pcs resource meta rsc_sap_{{ sap_instance_java_sid }}_ERS{{ sap_ha_ers_instance_number }} \
              resource-stickiness=3000
          register: sap_ha_cluster_resource_create
          changed_when: "'Assumed agent name' in sap_ha_cluster_resource_create.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary
            - sap_ha_ers_instance_number is defined

        - name: Create ASCS and ERS colocation
          ansible.builtin.shell:
            cmd: |
              /usr/sbin/pcs constraint colocation add g-{{ sap_instance_sid }}_AERS \
              with g-{{ sap_instance_sid }}_ASCS score=-5000
          register: sap_ha_cluster_resource_create
          changed_when: "'Assumed agent name' in sap_ha_cluster_resource_create.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary

        - name: Create ERS location
          ansible.builtin.shell:
            cmd: |
              /usr/sbin/pcs constraint location rsc_sap_{{ sap_instance_sid }}_ASCS{{ sap_ha_ascs_instance_number }} \
              rule score=2000 runs_ers_{{ sap_instance_sid }} eq 1
          register: sap_ha_cluster_resource_create
          changed_when: "'Assumed agent name' in sap_ha_cluster_resource_create.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary

        - name: Set start order
          ansible.builtin.shell:
            cmd: |
              /usr/sbin/pcs constraint order start g-{{ sap_instance_sid }}_ASCS \
              then start g-{{ sap_instance_sid }}_AERS kind=Optional symmetrical=false
          register: sap_ha_cluster_resource_create
          changed_when: "'Assumed agent name' in sap_ha_cluster_resource_create.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary

        - name: Set start order
          ansible.builtin.shell:
            cmd: |
              /usr/sbin/pcs constraint order start g-{{ sap_instance_sid }}_ASCS \
              then stop g-{{ sap_instance_sid }}_AERS kind=Optional symmetrical=false
          register: sap_ha_cluster_resource_create
          changed_when: "'Assumed agent name' in sap_ha_cluster_resource_create.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary

        - name: Activate first node
          ansible.builtin.command:
            cmd: |
              /usr/sbin/pcs node unstandby {{ sap_ha_primary }}
          register: sap_ha_cluster_node_standby
          changed_when: "'Assumed agent name' in sap_ha_cluster_node_standby.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary

        # Disable the stonith device
        - name: Disable stonith for the the Pacemaker high-availability cluster
          ansible.builtin.command:
            cmd: /usr/sbin/pcs property set stonith-enabled=false
          register: sap_ha_cluster_property_set
          changed_when: "'stonith-enabled: false' in sap_ha_cluster_property_set.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary

        # Ensure that the cluster is not in maintenance mode
        - name: Ensure Cluster is not in maintenance mode
          ansible.builtin.command:
            cmd: "/usr/sbin/pcs property set maintenance-mode=false"
          register: sap_ha_cluster_mode
          changed_when: "'error' not in sap_ha_cluster_mode.stdout"
          when:
            - ansible_facts['fqdn'] == sap_ha_primary
