---
- hosts: all
  become: true
  become_user: root

  vars:
    sap_anf_options: 'rw,vers=4,minorversion=1,hard,timeo=600,rsize=262144,wsize=262144,intr,noatime,lock,_netdev,sec=sys'

  tasks:
    - name: Configure shared disks
      block:
        # Create SAP mount points
        - name: Create SAP directory /sapmnt and /usr/sap
          ansible.builtin.file:
            path: '{{ item }}'
            state: directory
            mode: '0775'
          loop:
            - /sapmnt
            - /usr/sap

        # Mount logical SAP volumes
        - name: Mount ANF NFS on /sapmnt
          ansible.posix.mount:
            path: /sapmnt
            src: '{{ sap_anf_netweaver_sapmnt }}'
            opts: '{{ sap_anf_options }}'
            fstype: nfs
            state: mounted

        - name: Mount ANF NFS on /usr/sap
          ansible.posix.mount:
            path: /usr/sap
            src: '{{ sap_anf_netweaver_usrsap }}'
            opts: '{{ sap_anf_options }}'
            fstype: nfs
            state: mounted

      when:
        - ansible_facts['system_vendor'] == "Microsoft Corporation"
        - ansible_facts['product_name'] == "Virtual Machine"
        - ansible_facts['distribution'] == "RedHat"
        - sap_ha|bool == false
        - sap_anf|bool == true
