---
- hosts: all
  become: true
  become_user: root

  vars:
    nfs_options: "rw,vers=4,minorversion=1,hard,timeo=600,rsize=262144,wsize=262144,intr,noatime,lock,_netdev,sec=sys,suid"
    sap_anf_shared_saptrans: "10.242.91.139:/Global-saptrans"
    sap_anf_shared_sapmedia: "10.242.90.132:/sapdump"
    sap_apf_shared_itgdata: "sapstr01.file.core.windows.net:/sapstr01/global-itgdata"

  tasks:
    - name: Configure shared disks
      block:
        # Check if shared directories exist on local system
        - name: Check if /usr/sap/trans exists
          ansible.builtin.stat:
            path: /usr/sap/trans
          register: stat_result_saptrans

        - name: Check if /media/sap exists
          ansible.builtin.stat:
            path: /media/sap
          register: stat_result_sapmedia

        - name: Check if /itgdata/SID exists
          ansible.builtin.stat:
            path: "/itgdata/{{ sap_instance_sid }}"
          register: stat_result_itgdata

        # Create SAP mount points
        - name: Create shared directory /usr/sap/trans
          ansible.builtin.file:
            path: /usr/sap/trans
            group: sapsys
            state: directory
            mode: "0775"
          when:
            - stat_result_saptrans.stat.exists == false
            - sap_instance_type != "Router"
            - sap_instance_type != "Webdispatcher"
            - sap_instance_type != "DB"

        - name: Create shared directory /media/sap
          ansible.builtin.file:
            path: /media/sap
            state: directory
            mode: "0775"
          when:
            - stat_result_sapmedia.stat.exists == false

        - name: Create shared directory /itgdata/SID
          ansible.builtin.file:
            path: "/itgdata/{{ sap_instance_sid }}"
            group: sapsys
            state: directory
            mode: "0775"
          when:
            - stat_result_itgdata.stat.exists == false
            - sap_instance_type != "Router"
            - sap_instance_type != "Webdispatcher"
            - sap_instance_type != "DB"

        # Mount logical SAP volumes
        - name: Mount ANF NFS on /usr/sap/trans
          ansible.posix.mount:
            path: /usr/sap/trans
            src: "{{ sap_anf_shared_saptrans }}"
            opts: "{{ nfs_options }}"
            fstype: nfs
            state: mounted
          when:
            - sap_instance_type != "Router"
            - sap_instance_type != "Webdispatcher"
            - sap_instance_type != "DB"

        - name: Mount ANF NFS on /media/sap
          ansible.posix.mount:
            path: /media/sap
            src: "{{ sap_anf_shared_sapmedia }}"
            opts: "{{ nfs_options }}"
            fstype: nfs
            state: mounted

        - name: Mount APF NFS on /itgdata/SID
          ansible.posix.mount:
            path: "/itgdata/{{ sap_instance_sid }}"
            src: "{{ sap_apf_shared_itgdata }}"
            opts: "{{ nfs_options }}"
            fstype: nfs
            state: mounted
          when:
            - sap_instance_type != "Router"
            - sap_instance_type != "Webdispatcher"
            - sap_instance_type != "DB"

      when:
        - ansible_facts['system_vendor'] == "Microsoft Corporation"
        - ansible_facts['product_name'] == "Virtual Machine"
        - ansible_facts['distribution'] == "RedHat"
