---
- hosts: all
  become: true
  become_user: root

  vars:
    sap_anf_options: "rw,vers=4,minorversion=1,hard,timeo=600,rsize=262144,wsize=262144,intr,noatime,lock,_netdev,sec=sys,suid"

  tasks:
    # Install parted
    - name: Install parted
      ansible.builtin.package:
        name: parted
        state: present

    # Check if SAP disk exist on local system
    - name: Check if /dev/disk/azure/scsi1/lun0 exists
      ansible.builtin.stat:
        path: /dev/disk/azure/scsi1/lun0
      register: stat_result_lun0

    - name: Configure local SAP Netweaver disks
      block:
        # Setup disk layout for sap system
        - name: Use all disk space on /dev/disk/azure/scsi1/lun0 for LVM
          ansible.builtin.parted:
            device: "/dev/disk/azure/scsi1/lun0"
            number: 1
            flags: [lvm]
            state: present

        # Setup volume group for SAP
        - name: Create a volume group on /dev/disk/azure/scsi1/lun0-part1
          community.general.lvg:
            vg: sapvg
            pvs: /dev/disk/azure/scsi1/lun0-part1

        # Setup logical volumes for SAP
        - name: Create 48G logical volume usrsaplv in volume group sapvg (SAP)
          community.general.lvol:
            vg: sapvg
            lv: "{{ item }}"
            size: 48g
          loop:
            - usrsaplv

        - name: Create 48G logical volume sapmntlv in volume group sapvg (SAP)
          community.general.lvol:
            vg: sapvg
            lv: "{{ item }}"
            size: 48g
          loop:
            - sapmntlv
          when:
            - anf_storage|bool == false

        # Format logical SAP volumes
        - name: Create an xfs filesystem on /dev/sapvg/usrsaplv
          community.general.filesystem:
            fstype: xfs
            state: present
            dev: "{{ item }}"
          loop:
            - /dev/sapvg/usrsaplv

        - name: Create an xfs filesystem on /dev/sapvg/sapmntlv
          community.general.filesystem:
            fstype: xfs
            state: present
            dev: "{{ item }}"
          loop:
            - /dev/sapvg/sapmntlv
          when:
            - anf_storage|bool == false

        # Create SAP mount points
        - name: Create SAP directory /sapmnt
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
            mode: "0775"
          loop:
            - /usr/sap

        - name: Create SAP directory /sapmnt
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
            mode: "0775"
          loop:
            - /sapmnt
          when:
            - anf_storage|bool == false

        # Mount logical SAP volumes
        - name: mount the usrsaplv on /usr/sap
          ansible.posix.mount:
            path: /usr/sap
            src: /dev/sapvg/usrsaplv
            fstype: xfs
            state: mounted

        - name: mount the sapmntlv on /sapmnt
          ansible.posix.mount:
            path: /sapmnt
            src: /dev/sapvg/sapmntlv
            fstype: xfs
            state: mounted
          when:
            - anf_storage|bool == false

      when:
        - ansible_facts['system_vendor'] == "Microsoft Corporation"
        - ansible_facts['product_name'] == "Virtual Machine"
        - ansible_facts['distribution'] == "RedHat"
        - stat_result_lun0.stat.exists

    - name: Configure ANF SAP Netweaver disks
      block:
        # Create SAP mount points
        - name: Create SAP directory /sapmnt/SID for ABAP
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
            mode: "0775"
          loop:
            - "/sapmnt/{{ sap_instance_sid }}"

        - name: Create SAP directory /sapmnt/SID for JAVA
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
            mode: "0775"
          loop:
            - "/sapmnt/{{ sap_instance_java_sid }}"
          when:
            - sap_instance_java_sid is defined

        # Mount logical SAP volumes
        - name: Mount ANF NFS on /sapmnt/SID for ABAP
          ansible.posix.mount:
            path: "/sapmnt/{{ sap_instance_sid }}"
            src: "{{ sap_anf_netweaver_sapmnt }}"
            opts: "{{ sap_anf_options }}"
            fstype: nfs
            state: mounted

        - name: Mount ANF NFS on /sapmnt/SID for JAVA
          ansible.posix.mount:
            path: "/sapmnt/{{ sap_instance_java_sid }}"
            src: "{{ sap_anf_netweaver_java_sapmnt }}"
            opts: "{{ sap_anf_options }}"
            fstype: nfs
            state: mounted
          when:
            - sap_instance_java_sid is defined

        # Create SAP mount points
        - name: Create SAP directory /usr/sap/SID/SYS for ABAP
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
            mode: "0775"
          loop:
            - "/usr/sap/{{ sap_instance_sid }}/SYS"
          when:
            - sap_instance_type == "ASCS"

        - name: Create SAP directory /usr/sap/SID/SYS for JAVA
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory
            mode: "0775"
          loop:
            - "/usr/sap/{{ sap_instance_java_sid }}/SYS"
          when:
            - sap_instance_type == "ASCS"
            - sap_instance_java_sid is defined

        # Mount logical SAP volumes
        - name: Mount ANF NFS on /usr/sap/SID/SYS for ABAP
          ansible.posix.mount:
            path: "/usr/sap/{{ sap_instance_sid }}/SYS"
            src: "{{ sap_anf_netweaver_sapusr }}"
            opts: "{{ sap_anf_options }}"
            fstype: nfs
            state: mounted
          when:
            - sap_instance_type == "ASCS"

        - name: Mount ANF NFS on /usr/sap/SID/SYS for JAVA
          ansible.posix.mount:
            path: "/usr/sap/{{ sap_instance_java_sid }}/SYS"
            src: "{{ sap_anf_netweaver_java_sapusr }}"
            opts: "{{ sap_anf_options }}"
            fstype: nfs
            state: mounted
          when:
            - sap_instance_type == "ASCS"
            - sap_instance_java_sid is defined

      when:
        - ansible_facts['system_vendor'] == "Microsoft Corporation"
        - ansible_facts['product_name'] == "Virtual Machine"
        - ansible_facts['distribution'] == "RedHat"
        - anf_storage
