---
- hosts: all
  become: true
  become_user: root

  vars:
    sap_anf_options: 'rw,vers=4,minorversion=1,hard,timeo=600,rsize=262144,wsize=262144,intr,noatime,lock,_netdev,sec=sys'

  tasks:
    - name: Configure shared disks
      block:
        # Create SAP mount points
        - name: Create SAP directory /sapmnt/SID
          ansible.builtin.file:
            path: '{{ item }}'
            state: directory
            mode: '0775'
          loop:
            - '/sapmnt/{{ sap_instance_sid }}'

        # Mount logical SAP volumes
        - name: Mount ANF NFS on /sapmnt/SID
          ansible.posix.mount:
            path: '/sapmnt/{{ sap_instance_sid }}'
            src: '{{ sap_anf_netweaver_sapmnt }}'
            opts: '{{ sap_anf_options }}'
            fstype: nfs
            state: mounted

        # Create SAP mount points
        - name: Create SAP directory /usr/sap/SID/SYS
          ansible.builtin.file:
            path: '{{ item }}'
            state: directory
            mode: '0775'
          loop:
            - '/usr/sap/{{ sap_instance_sid }}/SYS'
          when:
            - sap_instance_type == "ASCS"

        # Mount logical SAP volumes
        - name: Mount ANF NFS on /usr/sap/SID/SYS
          ansible.posix.mount:
            path: '/usr/sap/{{ sap_instance_sid }}/SYS'
            src: '{{ sap_anf_netweaver_sapusr }}'
            opts: '{{ sap_anf_options }}'
            fstype: nfs
            state: mounted
          when:
            - sap_instance_type == "ASCS"

      when:
        - ansible_facts['system_vendor'] == "Microsoft Corporation"
        - ansible_facts['product_name'] == "Virtual Machine"
        - ansible_facts['distribution'] == "RedHat"
        - sap_anf|bool == true
