---
- name: Configure SAP shared disks
  hosts: all
  become: true
  become_user: root

  vars:
    nfs_options: "rw,vers=4,minorversion=1,hard,timeo=600,rsize=262144,wsize=262144,intr,noatime,lock,_netdev,sec=sys,suid"
    sap_shared_saptrans: "10.242.143.1:/global-saptrans"
    sap_shared_sapmedia: "10.242.143.2:/sapmedia"
    sap_shared_backupmedia: "10.242.143.3:/global-backup"
    sap_shared_data: "10.242.143.4:/global-sapdata"

  tasks:
    - name: Configure shared disks
      when:
        - ansible_facts['os_family'] == "RedHat"
        - sap_instance_sid is defined
      block:
        - name: Check if /usr/sap/trans exists
          ansible.builtin.stat:
            path: /usr/sap/trans
          register: stat_result_saptrans

        - name: Check if /media/sap exists
          ansible.builtin.stat:
            path: /media/sap
          register: stat_result_sapmedia

        - name: Check if /media/backup exists
          ansible.builtin.stat:
            path: /media/backup
          register: stat_result_backupmedia

        - name: Check if /sapdata/SID exists
          ansible.builtin.stat:
            path: "/sapdata/{{ sap_instance_sid }}"
          register: stat_result_sapdata

        - name: Create shared directory /usr/sap/trans
          ansible.builtin.file:
            path: /usr/sap/trans
            group: sapsys
            state: directory
            mode: "0775"
          when:
            - not stat_result_saptrans.stat.exists
            - sap_instance_type != "Router"
            - sap_instance_type != "Webdispatcher"
            - sap_instance_type != "DB"

        - name: Create shared directory /media/sap
          ansible.builtin.file:
            path: /media/sap
            state: directory
            mode: "0775"
          when:
            - not stat_result_sapmedia.stat.exists

        - name: Create shared directory /media/backup
          ansible.builtin.file:
            path: /media/backup
            state: directory
            mode: "0775"
          when:
            - not stat_result_backupmedia.stat.exists

        - name: Create shared directory /sapdata/SID
          ansible.builtin.file:
            path: "/sapdata/{{ sap_instance_sid }}"
            group: sapsys
            state: directory
            mode: "0775"
          when:
            - not stat_result_sapdata.stat.exists
            - sap_instance_type != "Router"
            - sap_instance_type != "Webdispatcher"
            - sap_instance_type != "DB"

        - name: Mount NFS on /usr/sap/trans
          ansible.posix.mount:
            path: /usr/sap/trans
            src: "{{ sap_shared_saptrans }}"
            opts: "{{ nfs_options }}"
            fstype: nfs
            state: mounted
          when:
            - sap_instance_type != "Router"
            - sap_instance_type != "Webdispatcher"
            - sap_instance_type != "DB"

        - name: Mount NFS on /media/sap
          ansible.posix.mount:
            path: /media/sap
            src: "{{ sap_shared_sapmedia }}"
            opts: "{{ nfs_options }}"
            fstype: nfs
            state: mounted

        - name: Mount NFS on /media/backup
          ansible.posix.mount:
            path: /media/backup
            src: "{{ sap_shared_backupmedia }}"
            opts: "{{ nfs_options }}"
            fstype: nfs
            state: mounted

        - name: Mount NFS on /sapdata/SID
          ansible.posix.mount:
            path: "/sapdata/{{ sap_instance_sid }}"
            src: "{{ sap_shared_sapdata }}/{{ sap_instance_sid }}"
            opts: "{{ nfs_options }}"
            fstype: nfs
            state: mounted
          when:
            - sap_instance_type != "Router"
            - sap_instance_type != "Webdispatcher"
            - sap_instance_type != "DB"
